name: CI

on: [push]

jobs:
  build:

    name: "${{ matrix.sdk-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        sdk-version: [stable] #, dev]
        # flutter-type: [git, zip]
        
    steps:

      - uses: actions/checkout@v1

      - name: Setup Dart ${{ matrix.dart-version }}
        uses: DanTup/gh-actions/setup-dart@master
        with:
          channel: ${{ matrix.sdk-version }}

      - name: Setup Flutter ${{ matrix.sdk-version }}
        uses: DanTup/gh-actions/setup-flutter@master
        with:
          channel: ${{ matrix.sdk-version }}
          # Zip not currently supported, since Flutter has .tar.xz and the GH toolkit doesn't support this
          # (also, in testing it was lower than the Git version)
          # zip: ${{ matrix.flutter-type == 'zip' }}

      - name: Print Dart version
        run: dart --version

      - name: Print Flutter version
        run: flutter --version

